// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frezmwtubianybvrkxmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyZXptd3R1YmlhbnlidnJreG12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1Nzk0MTQsImV4cCI6MjA1ODE1NTQxNH0.mtfXNdc8NZHEXcK_iLYZ6Uckh9NKLnvzpcbwLLDnwq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);